lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
title: "/stochastictalk"
url: https://stochastictalk.github.io
baseurl: ""
remote_theme: "tareqdandachi/jekyll-shell-theme"
plugins:
- jekyll-remote-theme 
- jemoji
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-last-modified-at
gist:
  noscript: false
github_username: stochastictalk
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
header_pages:
  - index.md
last-modified-at:
    date-format: '%y-%b-%d'
toc:
  enabled: true
  start_level: 1
  end_level: 4