source: .
title: "/stochastictalk"
url: https://stochastictalk.github.io
repository: stochastictalk/stochastictalk.github.io
github_username: stochastictalk
baseurl: ""
header_pages:
  - index.md
  - posts.md

plugins:
- jekyll-remote-theme 
- jemoji
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-last-modified-at
- jekyll-responsive-image
- jekyll-youtube
remote_theme: "tareqdandachi/jekyll-shell-theme"

responsive_image:
  template: _includes/responsive-image.html
  sizes:
    - width: 320
    - width: 480
    - width: 800
base_path: assets

